name: CI
on:
  pull_request:
    branches: 
        - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - NodeVersion: 20.14.x
            NodeVersionDisplayName: 20
            OS: ubuntu-latest
    name: Node.js v${{ matrix.NodeVersionDisplayName }} (${{ matrix.OS }})
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Config Git User
        # should be turn to ci user
        run: |
          git config --local user.name "lllux"
          git config --local user.email "lllux0218@gmail.com"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            common/temp/pnpm-local
            common/temp/pnpm-store
            common/temp/install-run
          key: ${{ runner.os }}-rush-store-${{ hashFiles('common/config/subspaces/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-rush-store-main
            ${{ runner.os }}-rush-store

      - name: Install Dependencies
        run: npm install

      - name: Build all
        run: npm run build
        continue-on-error: true

      - name: Test:cov all
        run: npm run test:unit -- --coverage
        continue-on-error: true

    #   - name: Lint all
    #     run: npm run lint
    #     continue-on-error: true

      # - name: Increment TS Check
      #   run: node infra/rush-x/bin/run increment --action ts-check -f "${{ steps.changed-files.outputs.all_changed_files }}" -s ' '
      #   continue-on-error: true

      - name: Package Audit
        run: npm audit --json

      - name: Fail if any report failed
        # NOTICE: To show all reports from the previous steps, the last step should check if any jobs failed.
        if: env.REPORT_RESULT == 'failed'
        run: echo "::notice::Please check 「 Summary 」 for detail info" && exit 1

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true